name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Atualiza automaticamente todo dia à meia-noite
  workflow_dispatch: # Permite rodar manualmente

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate and publish snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: rafaelpr04
          outputs: |
            snake-output/snake.svg
            snake-output/snake-dark.svg?palette=github-dark
